config/routes.rb
	Rails.application.routes.draw do
	get 'pictures' => 'pictures#index'

end

Rails.application.routes.draw do
	root 'pictures#index'
	resources :pictures

end

app/models/picture.rb
class Picture < ActiveRecord::Base
	scope :newest_first, -> { order(created_at: :desc) }
	scope :most_recent_five, -> { newest_first.limit(5) }
	scope :created_before, ->(time) { where("created_at < ?", time) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

	def index
		@most_recent_pictures = Picture.most_recent_five
		@created_before = Picture.created_before(:time)
	end

	def show
		@picture = Picture.find(params[:id])
	end

	def new
		@picture = Picture.new
	end

	def create
		# make a new picture with what picture_params returns (which is a method we're calling)
		@picture = Picture.new(picture_params)
		if @picture.save
			# if the save for the picture was successful, go to index.html.erb
			redirect_to pictures_url
		else
			# otherwise render the view associated with the action :new (i.e. new.html.erb)
			render :new
		end
	end

	def edit
		@picture = Picture.find(params[:id])
	end

	def update
		@picture = Picture.find(params[:id])

		if @picture.update_attributes(picture_params)
			redirect_to pictures_path(:id)
		else
			render :edit
		end
	end

	def destroy
		@picture = Picture.find(params[:id])
		@picture.destroy
		redirect_to pictures_url
	end

	private
	def picture_params
		params.require(:picture).permit(:artist, :title, :url)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
	<html>
		<head>
			<title>Photogur</title>
			<%= stylesheet_link_tag		'application', media: 'all', 'data-turbolinks-track' => true %>
			<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
			<%= csrf_meta_tags %>
		</head>
		<body>
		
			<%= yield %>
		
		</body>
	</html>

app/views/pictures/edit.html.erb
<h1>Edit Picture</h1>

<p>
	<%= link_to "Back", @picture %>
</p>

<%= form_for @picture do |f| %>
	<p>
		<%= f.label :artist %><br>
		<%= f.text_field :artist %>
	</p>
	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</p>
	<p>
		<%= f.label :url %><br>
		<%= f.text_field :url %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/pictures/index.html.erb
<h1>Most recent pictures</h1>

<%= link_to "New Picture", picture_path(:new) %>

<ul>
	<% @most_recent_pictures.each do |picture| %>
		<li><%= picture.title %> , <%= picture.artist %></li>
		<%= link_to image_tag(picture.url), picture_path(:picture_id) %>
		<li><%= link_to "Edit", edit_picture_path(picture) %> <%= link_to "Delete", picture, method: :delete, data: {confirm: "Are you sure you want to delete this picture?"} %></li>
	<% end %>
</ul>

<h3>Pictures posted more than a month ago:</h3>

<ul>
	<% Picture.created_before(1.month.ago).each do |picture| %>
	<li><%= picture.title %></li>
	<% end %>
</ul>

<h3>Total number of pictures posted more than a month ago: <%= Picture.created_before(1.month.ago).count %></h3>

app/views/pictures/new.html.erb
<h1>Add a picture</h1>
<%= link_to "Back to Pictures", pictures_url %>

<%= form_for(@picture) do |f| %>
	<p>
		<%= f.label :artist %><br>
		<%= f.text_field :artist %>
	</p>
	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</p>
	<p>
		<%= f.label :url %><br>
		<%= f.text_field :url %>
	</p>
	<p>
		<%= f.submit "Save" %>
	</p>
<% end %>

app/views/pictures/show.html.erb
<%= link_to "Back to Pictures", pictures_url %> | <%= link_to "Edit", edit_picture_path(@picture) %> | <%= link_to "Delete", @picture, method: :delete, data: {confirm: "Are you sure you want to delete this picture?"}	%>


<p><%= @picture.title %>, <%= @picture.artist %></p>
<img src="<%= @picture.url %>">